version: '3.4'

services:
  common-api:
      build:
        context: ./common-api
      restart: always
      depends_on:
        - postgres
      ports:
        - "3000:3000"
      command:
        - /bin/sh
        - -c
        - |
          npm run migrate
          npm run seed
          nodemon ./bin/www
      volumes:
        - ./common-api:/usr/src/app
        - common-deps:/usr/src/app/node_modules
      environment:
        - NODE_ENV=development
        - CNFG_DB__CONNECTION__HOST=postgres
        - CNFG_DB__CONNECTION__USER=postgres
        - CNFG_DB__CONNECTION__PASSWORD=password
        - CNFG_DB__CONNECTION__DATABASE=dev_data
        - CNFG_APP__HOST=0.0.0.0
        - CNFG_APP__PORT=3000
  frontend:
      build:
        context: ./frontend
      restart: always
      depends_on:
        - common-api
      ports:
        - "4200:4200"
      command:
        - /bin/sh
        - -c
        - |
          npm start
      volumes:
        - ./frontend:/usr/src/app
        - front-deps:/usr/src/app/node_modules
      environment:
        - NODE_ENV=development
  postgres:
    image: postgres:9.6.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dev_data
    volumes:
      - db-data:/var/lib/postgresql/data/
  adminer:
    image: adminer
    restart: always
    depends_on:
        - postgres
    ports:
      - "8080:8080"
volumes:
  common-deps:
  front-deps:
  db-data:
    driver: local