version: '3.4'

services:
  postgres:
    image: postgres:9.6.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dev_data
  common-api:
      build:
        context: ./common-api
      restart: always
      depends_on:
        - postgres
      ports:
        - "3000:3000"
      command: npm start 
      volumes:
        - ./common-api:/usr/src/app
        - /usr/src/app/node_modules
      environment:
        - NODE_ENV=development
        - DB_HOST=postgres
        - DB_USER=postgres
        - DB_PASS=password
        - DB_NAME=dev_data
        - APP_HOST=0.0.0.0
        - APP_PORT=3000